CREATE TABLE IF NOT EXISTS TWITTER.HAPPY_HASHTAGS (
    NAME character(280),
    DATEHOUR timestamp(0),
    HAPPINESS integer,
    PRIMARY KEY (NAME, DATEHOUR)
);
ALTER TABLE TWITTER.HAPPY_HASHTAGS
    OWNER to postgres;